// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: routes.generate
// Edit instead: the routes.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run routes.generate --site forge-site
/*
<MODULE_CONTRACT>
<purpose>RFC-0899: Generated access protection middleware entry point. Re-exports shared middleware from werkstatt-shared.</purpose>
<non-goals>
  <item>Do not implement middleware logic here — logic lives in @warpgogol/werkstatt-shared/middleware/access-protection.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by routes.generate (RFC-0899).</item>
  <item>GENERATED — do not edit directly; rerun routes.generate.</item>
</CHANGE_SUMMARY>
*/

// @ai-invariant: Re-exports shared access protection middleware. No local logic.
// RFC-0899: access protection for dev/alt subdomains via Basic Auth PIN.
export { accessProtectionMiddleware as default } from "@warpgogol/werkstatt-shared/middleware/access-protection";
