// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: agent.markdown-negotiation.generate
// Edit instead: the agent.markdown-negotiation.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run agent.markdown-negotiation.generate --site forge-site
/*
<MODULE_CONTRACT>
<purpose>Markdown content negotiation middleware generated by agent.markdown-negotiation.generate (RFC-0785).</purpose>
<keywords>middleware, content negotiation, markdown, agent, RFC-0785</keywords>
<responsibilities>
  <item>Intercept GET requests with Accept: text/markdown and serve the .md twin if it exists.</item>
  <item>Pass through to next() for all other requests (non-GET, no Accept: text/markdown, no twin found).</item>
  <item>Set Vary: Accept on ALL page responses (negotiated and pass-through) to prevent CDN cache poisoning.</item>
</responsibilities>
<non-goals>
  <item>Do not generate markdown twins — page.markdown.generate (RFC-0166) owns that.</item>
  <item>Do not serve .md files with Content-Type — _headers (RFC-0315) handles direct .md requests.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by agent.markdown-negotiation.generate (RFC-0785).</item>
  <item>GENERATED — do not edit directly; rerun agent.markdown-negotiation.generate.</item>
  <item>Add export default onRequest so middleware.ts can import as default (matches language-redirect and retired-tombstones templates).</item>
  <item>Add Vary: Accept to ALL page responses (not just negotiated) to prevent CDN serving cached HTML for Accept: text/markdown.</item>
  <item>Replace hardcoded isPageRoute extension regex with ico|png|jpg|jpeg|webp|avif|gif|bmp|svg|css|js|mjs|json|txt|xml|woff|woff2|ttf|otf|webmanifest|md|pdf|webm|mp4|wasm|map|m3u8|ts|html|ndjson|vtt|yaml placeholder injected from PAGE_ROUTE_EXCLUDED_EXTENSIONS — single source of truth in @warpgogol/werkstatt-shared/share/redirects.</item>
</CHANGE_SUMMARY>
*/

// @ai-invariant: Runs on every GET request. Fast Accept header check before any fetch.
// RFC-0785: markdown content negotiation for agent requests.
import { defineMiddleware } from "astro:middleware";
import { markdownTwinUrlPath } from "@warpgogol/werkstatt-shared/share/semantic";

const SUPPORTED_LANGS = ["en"];

function isPageRoute(pathname: string): boolean {
  if (pathname.startsWith("/api/")) return false;
  if (pathname.startsWith("/.well-known/")) return false;
  if (/\.({{EXCLUDED_EXTENSIONS}})$/.test(pathname))
    return false;
  return true;
}

function addVaryAccept(response: Response): Response {
  const headers = new Headers(response.headers);
  headers.set("Vary", "Accept");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export const onRequest = defineMiddleware(async (context, next) => {
  const { request } = context;
  if (request.method !== "GET") return next();

  const url = new URL(request.url);
  if (!isPageRoute(url.pathname)) return next();

  const accept = request.headers.get("Accept") ?? "";
  if (!accept.includes("text/markdown")) {
    const response = await next();
    return addVaryAccept(response);
  }

  const twinPath = markdownTwinUrlPath(url.pathname, { supportedLangs: SUPPORTED_LANGS });
  const twinUrl = new URL(twinPath, url.origin);
  const twinResponse = await fetch(twinUrl);
  if (!twinResponse.ok) {
    const response = await next();
    return addVaryAccept(response);
  }

  const body = await twinResponse.text();
  return new Response(body, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Vary": "Accept",
      "Cache-Control": "public, max-age=300",
    },
  });
});

export default onRequest;
