schemaVersion: 1.0.0
id: forge-site
cosmicStar: Sirius
mirrors:
  - path: ../systems-cache/forge-site
    storageType: non-bare
  - path: ../systems-git/forge-site
    storageType: bare
pinnedPlatform: 6.289.47
status: active
registeredAt: 2026-09-13T15:04:31.824Z
notes: ""

