schemaVersion: 1.0.0
id: forge-site
cosmicStar: Sirius
mirrors:
  - path: ../systems-cache/forge-site
    storageType: non-bare
  - path: ../systems-git/forge-site
    storageType: bare
  - path: git@github.com:syrokomskyi/forge-site.git
    storageType: bare
pinnedPlatform: 6.297.3
status: active
registeredAt: 2026-09-13T15:04:31.824Z
deployment:
  adapter: github-pages
  channels:
    dev:
      workerName: syrokomskyi/forge-site
      url: https://syrokomskyi.github.io/forge-site
    alt:
      workerName: syrokomskyi/forge-site
      url: https://syrokomskyi.github.io/forge-site
    main:
      workerName: syrokomskyi/forge-site
      url: https://syrokomskyi.github.io/forge-site
notes: ""

