// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: kernel.wire
// Edit instead: packages/werkstatt/src/kernel/templates/wire/tools/modules/deploy.module.template.ts
// Regenerate:   pnpm exec werkstatt run kernel.wire --site forge-site
/*
<MODULE_CONTRACT>
<purpose>Deploy module registering client export command.</purpose>
<non-goals>
  <item>Do not implement export logic here — delegate to site-kernel-deploy.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
import type { ModuleExport } from "@warpgogol/werkstatt-engine/runtime/desired-state";
import { runClientExport } from "./../runtime/client-export";

export const deployModule: ModuleExport = {
  name: "deploy",
  version: "0.1.0",
  declarations: [],
  commands: [
    {
      name: "client.export",
      description: "Export the current app for client delivery.",
      scope: "app",
      mutatesState: true,
      cacheable: false,
      writes: ["../clients/<app>/**"],
      reads: ["<app>/dist/**"],
      flags: {},
      execute: runClientExport,
    }
  ],
  pipelines: [],
};
