// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: kernel.wire
// Edit instead: packages/werkstatt/src/kernel/templates/wire/tools/runtime/re-export.template.ts
// Regenerate:   pnpm exec werkstatt run kernel.wire --site forge-warpgogol
/*
<MODULE_CONTRACT>
<purpose>Re-export runtime commands from @warpgogol/werkstatt-engine/integrity.</purpose>
<non-goals>
  <item>Do not implement logic locally — this file is a thin proxy.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by kernel.wire (RFC-0078).</item>
</CHANGE_SUMMARY>
*/
export {
  runIntegrityInit,
  runIntegrityUpdate,
  runIntegrityVerify,
  runIntegrityBuildRecord,
  runIntegritySign,
  runIntegrityVerifyRelease,
  runIntegrityGenerateSigningKeypair,
  runIntegrityBackfillRevisions
} from "@warpgogol/werkstatt-engine/integrity";
