// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: agent.routes.generate
// Edit instead: the agent.routes.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run agent.routes.generate
// Section-owned Agent Gate route (RFC-1116). Handler logic lives once in
// @warpgogol/agent-gate; this file is a thin re-export emitted by
// agent.routes.generate. Do not edit — rerun agent.routes.generate.
export const prerender = false;
import agentSurfaceManifest from "../../../agent-surface.generated.json";
import { createAgentHealthRoute } from "@warpgogol/werkstatt-engine/agent-gate/astro";

const route = createAgentHealthRoute(agentSurfaceManifest as never);
export const GET = route.GET;
export const OPTIONS = route.OPTIONS;
