// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: agent.search.route.generate
// Edit instead: the agent.search.route.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run agent.search.route.generate
// RFC-0954: Agent semantic search route. Handler logic lives once in
// @warpgogol/werkstatt-engine/agent-gate/astro; this file is a thin re-export
// emitted by agent.search.route.generate. Do not edit — rerun agent.search.route.generate.
export const prerender = false;
import agentSurfaceManifest from "../../../agent-surface.generated.json";
import { createAgentSearchRoute } from "@warpgogol/werkstatt-engine/agent-gate/astro";

const route = createAgentSearchRoute(agentSurfaceManifest as never);
export const GET = route.GET;
export const POST = route.POST;
export const OPTIONS = route.OPTIONS;
