// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: routes.generate
// Edit instead: the routes.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run routes.generate --site forge-site
/*
<MODULE_CONTRACT>
<purpose>Centralizes the definition of content collections for structured data access in the application.</purpose>
<non-goals>
  <item>Do not source content from src/data/**.</item>
  <item>Do not manage transport or configuration logic.</item>
  <item>Do not include unrelated business logic.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-1097: step 6 — compass.migrate codemod run

Mechanical v1 to v2 header migration across the workspace: 942 files rewritten — CHANGE_SUMMARY windows collapsed into history, forbidden v1 blocks stripped, KEY_DECISIONS seeded from @ai-invariant comments (5 files) or TODO placeholders (103 files), blocks reordered to canonical order.</item>
  <item>RFC-1097: sweep — werkstatt-engine clean

Sweep batch 4: 73 Compass headers on headerless engine files (certification, component-runtime, isolation, evolution, testing), real KEY_DECISIONS on 75 files (kernel, cache, dht, swim, gitmesh, runtime), ~80 purpose expansions (CONTRACT-02/PURPOSE-02), non-goals on 13 CONTRACT-03 files, CS-07 history literal fix repo-wide (253 files). Policy: .template.ts/.template.astro excludedPaths. werkstatt-engine now 0 diagnostics.</item>
</CHANGE_SUMMARY>
*/

// [DNA-04][DNA-10] Content collections are the ONLY source of typed, validated content.
// Register all collections here. Export their types for page routes to use.
//
// Rules:
// - Collections for component copy: use markdownCollectionLoader
// - Collections for page shell: use markdownCollectionLoader
// - Collections for entity data (pSEO): use markdownCollectionLoader
// - Never source content from src/data/** (removed architecture)

import { defineCollection } from "astro:content";
import { glob } from "astro/loaders";
import { z } from "astro/zod";
import { markdownCollectionLoader } from "@warpgogol/werkstatt-site/share/astro/loaders";
import { fsDataCollectionLoader } from "@warpgogol/werkstatt-site/content-source";
import { pbpCollections } from "@warpgogol/werkstatt-site/pbp/astro";
import { createFaqCollection } from "@warpgogol/werkstatt-site/faq/astro";
import { toDataEntryId } from "@warpgogol/werkstatt-shared/content";
import { systemCollectionSchema } from "@warpgogol/werkstatt-shared/ontology/schemas";

const system = defineCollection({
  loader: glob({
    pattern: "system.md",
    base: "src/content",
    generateId: () => "system",
  }),
  schema: systemCollectionSchema,
});

// Loads all .md files from src/content/pages/ as the "pages" collection.
const pages = defineCollection({
  loader: markdownCollectionLoader("src/content/pages"),
  schema: z.object({}).loose(),
});

const prose = defineCollection({
  loader: markdownCollectionLoader("src/content/prose"),
  schema: z.object({}).loose(),
});

const site = defineCollection({
  loader: markdownCollectionLoader("src/content/site"),
  schema: z.object({}).loose(),
});

// Loads navigation.md files from src/content/navigation/{lang}/ as the "navigation" collection (RFC-0044).
// Contains content-declared navigation target definitions for client-editable navigation structure.
// Runtime validation in navigation.ts ensures data structure correctness.
const navigation = defineCollection({
  loader: markdownCollectionLoader("src/content/navigation"),
  schema: z.object({}).loose(),
});

// Loads person records from src/content/people/{lang}/ as the "people" collection (RFC-0200).
// Used by the data-driven People section (@warpgogol/werkstatt-site/share/astro/people.ts).
const people = defineCollection({
  loader: fsDataCollectionLoader({
    base: "src/content/people",
    generateId: (entry) => toDataEntryId(entry),
  }),
  schema: z.object({}).catchall(z.any()),
});

const faq = createFaqCollection();

export const collections = {
  ...pbpCollections,
  system,
  pages,
  prose,
  site,
  navigation,
  people,
  ...faq,
  // Future collections (pSEO entities) are added here:
  // industries,
  // cities,
  // topics,
};

// Page-data and component-content types are exported from @warpgogol/werkstatt-site/ui and
// @warpgogol/werkstatt-shared. Apps must not re-declare them here.
