// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: routes.generate
// Edit instead: the routes.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run routes.generate --site forge-site
/*
<MODULE_CONTRACT>
<purpose>Defines type declarations for Astro components and environment variables.</purpose>
<non-goals>
  <item>Do not implement runtime logic or component behavior.</item>
  <item>Do not manage application state or side effects.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-1097: step 6 — compass.migrate codemod run

Mechanical v1 to v2 header migration across the workspace: 942 files rewritten — CHANGE_SUMMARY windows collapsed into history, forbidden v1 blocks stripped, KEY_DECISIONS seeded from @ai-invariant comments (5 files) or TODO placeholders (103 files), blocks reordered to canonical order.</item>
  <item>RFC-1097: sweep — werkstatt-engine clean

Sweep batch 4: 73 Compass headers on headerless engine files (certification, component-runtime, isolation, evolution, testing), real KEY_DECISIONS on 75 files (kernel, cache, dht, swim, gitmesh, runtime), ~80 purpose expansions (CONTRACT-02/PURPOSE-02), non-goals on 13 CONTRACT-03 files, CS-07 history literal fix repo-wide (253 files). Policy: .template.ts/.template.astro excludedPaths. werkstatt-engine now 0 diagnostics.</item>
</CHANGE_SUMMARY>
*/

/// <reference path="../.astro/types.d.ts" />
/// <reference types="astro/client" />

declare module "*.astro" {
  const Component: (props: Record<string, unknown>) => unknown;
  export default Component;
}

declare module "*.yaml" {
  const value: unknown;
  export default value;
}

// [RFC-0149] Astro 6 removed `Astro.locals.runtime`. Runtime secrets are read via
// `astro:env/server`; the Cloudflare `cf`/exec-context surface (if ever needed) is on
// `Astro.request.cf` / `Astro.locals.cfContext`. Do not reintroduce a `Runtime<Env>` type.
declare namespace App {
  interface Locals {
    language?: string;
  }
}
