// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: routes.generate
// Edit instead: the routes.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run routes.generate --site forge-site
/*
<MODULE_CONTRACT>
<purpose>Root middleware entry point that chains all Astro request middleware.</purpose>
<non-goals>
  <item>Do not implement middleware logic here — delegate to sub-modules.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>RFC-0589: chain retired-tombstone middleware first for 410 Gone handling.</item>
  <item>RFC-0785: chain markdown-negotiation middleware for agent content negotiation.</item>
  <item>RFC-0899: chain access-protection middleware first for dev/alt subdomain auth gate.</item>
  <item>RFC-1097: step 6 — compass.migrate codemod run

Mechanical v1 to v2 header migration across the workspace: 942 files rewritten — CHANGE_SUMMARY windows collapsed into history, forbidden v1 blocks stripped, KEY_DECISIONS seeded from @ai-invariant comments (5 files) or TODO placeholders (103 files), blocks reordered to canonical order.</item>
  <item>RFC-1097: sweep — werkstatt-engine clean

Sweep batch 4: 73 Compass headers on headerless engine files (certification, component-runtime, isolation, evolution, testing), real KEY_DECISIONS on 75 files (kernel, cache, dht, swim, gitmesh, runtime), ~80 purpose expansions (CONTRACT-02/PURPOSE-02), non-goals on 13 CONTRACT-03 files, CS-07 history literal fix repo-wide (253 files). Policy: .template.ts/.template.astro excludedPaths. werkstatt-engine now 0 diagnostics.</item>
  <history>RFC-0569</history>
</CHANGE_SUMMARY>
*/
// @ai-invariant: High-risk module. Middleware chain. Access protection runs first, then tombstone, then language redirect, then markdown negotiation.
// RFC-0899: access-protection middleware gates dev/alt subdomains with Basic Auth PIN.
// RFC-0569: dev-normalize middleware applies egress text normalization in dev mode.
// RFC-0589: retired-tombstone middleware returns 410 Gone for retired page routes.
// RFC-0785: markdown-negotiation middleware serves .md twins for Accept: text/markdown requests.
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { sequence } from "astro:middleware";
import accessProtectionMiddleware from "./middleware/access-protection";
import languageRedirectMiddleware from "./middleware/language-redirect";
import tombstoneMiddleware from "./middleware/retired-tombstones";
import markdownNegotiationMiddleware from "./middleware/markdown-negotiation";
import { createDevNormalizeMiddleware, resolveNormalizeConfig } from "@warpgogol/werkstatt-shared/text/text-normalize";
import { loadSystemManifestSync } from "@warpgogol/werkstatt-site/content";

const devNormalize = import.meta.env.DEV
  ? createDevNormalizeMiddleware(
      resolveNormalizeConfig(
        loadSystemManifestSync(
          resolve(dirname(fileURLToPath(import.meta.url)), "content"),
        ).manifest,
      ),
    )
  : null;

export const onRequest = import.meta.env.DEV
  ? sequence(accessProtectionMiddleware, tombstoneMiddleware, languageRedirectMiddleware, markdownNegotiationMiddleware, devNormalize!)
  : sequence(accessProtectionMiddleware, tombstoneMiddleware, languageRedirectMiddleware, markdownNegotiationMiddleware);
