// GENERATED. Do not change this line unless the file contains project specific changes.
// DO NOT EDIT THIS FILE. Changes are overwritten on the next build.
// Owner command: agent.markdown-negotiation.generate
// Edit instead: the agent.markdown-negotiation.generate generator source (not this file).
// Regenerate:   pnpm exec werkstatt run agent.markdown-negotiation.generate --site forge-warpgogol
/*
<MODULE_CONTRACT>
<purpose>Custom Cloudflare Worker entry point generated by agent.markdown-negotiation.generate (RFC-0785).
Wraps the Astro Cloudflare adapter handler to intercept Accept: text/markdown requests
before matchStaticAsset short-circuits prerendered pages (Astro issue #16252).</purpose>
<keywords>worker, cloudflare, content negotiation, markdown, agent, RFC-0785</keywords>
<responsibilities>
  <item>Intercept GET requests with Accept: text/markdown and serve the .md twin if it exists.</item>
  <item>Set Vary: Accept on ALL page responses (negotiated and pass-through) to prevent CDN cache poisoning.</item>
  <item>Pass through to Astro handler for all other requests (non-GET, no Accept: text/markdown, no twin found).</item>
  <item>Fetch .md twins from env.ASSETS binding directly (same-origin static asset).</item>
</responsibilities>
<non-goals>
  <item>Do not generate markdown twins — page.markdown.generate (RFC-0166) owns that.</item>
  <item>Do not serve .md files with Content-Type — _headers (RFC-0315) handles direct .md requests.</item>
  <item>Do not handle non-page routes (API, .well-known, static assets) — pass through to Astro handler.</item>
</non-goals>
</MODULE_CONTRACT>
<CHANGE_SUMMARY>
  <item>Generated by agent.markdown-negotiation.generate (RFC-0785).</item>
  <item>GENERATED — do not edit directly; rerun agent.markdown-negotiation.generate.</item>
  <item>Custom Worker entry point — wraps Astro handler to run content negotiation before matchStaticAsset.</item>
  <item>Add Vary: Accept to ALL page responses to prevent CDN serving cached HTML for Accept: text/markdown.</item>
  <item>Fix isPageRoute to exclude webp, avif, gif, bmp, mjs, webm, mp4, wasm, map — without these, the Worker 308-redirects image requests to trailing-slash URLs (e.g. 1280.webp/), causing 404s.</item>
  <item>RFC-0908: add www→apex host canonicalization redirect (301) before request processing.</item>
  <item>Fix isPageRoute to exclude m3u8, ts — without these, the Worker 308-redirects HLS manifest/segment requests to trailing-slash URLs (e.g. master.m3u8/), causing 404s for feature videos.</item>
</CHANGE_SUMMARY>
*/

// @ai-invariant: Wraps Astro Cloudflare handler. Runs before matchStaticAsset for prerendered pages.
// RFC-0785: markdown content negotiation for agent requests.
import { default as astroHandler } from "@astrojs/cloudflare/entrypoints/server";
import { markdownTwinUrlPath } from "@warpgogol/werkstatt-shared/share/semantic";
import { checkAccessProtection, addNoIndexHeaderIfNeeded } from "@warpgogol/werkstatt-shared/share/middleware/access-protection";

const SUPPORTED_LANGS = ["en"];

function isPageRoute(pathname: string): boolean {
  if (pathname.startsWith("/api/")) return false;
  if (pathname.startsWith("/.well-known/")) return false;
  if (/\.(ico|png|jpg|jpeg|webp|avif|gif|bmp|svg|css|js|mjs|json|txt|xml|woff|woff2|ttf|otf|webmanifest|md|pdf|webm|mp4|wasm|map|m3u8|ts|html|ndjson|vtt|yaml)$/.test(pathname))
    return false;
  return true;
}

function addVaryAccept(response: Response): Response {
  const headers = new Headers(response.headers);
  headers.set("Vary", "Accept");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

export default {
  async fetch(request: Request, env: Record<string, unknown>, ctx: ExecutionContext): Promise<Response> {
    // RFC-0899: Access protection for dev/alt subdomains — must run before any
    // request processing, including static asset serving. Astro middleware cannot
    // intercept prerendered static pages (output: "static"), so the check runs here.
    const denied = checkAccessProtection(request, env);
    if (denied) return denied;

    // RFC-0908: www→apex host canonicalization redirect.
    // Redirect www.warpgogol.com → warpgogol.com (preserving path and query).
    const canonicalUrl = new URL(request.url);
    if (canonicalUrl.hostname.startsWith("www.")) {
      canonicalUrl.hostname = canonicalUrl.hostname.slice(4);
      return Response.redirect(canonicalUrl.toString(), 301);
    }

    if (request.method !== "GET") {
      const response = await astroHandler.fetch(request, env, ctx);
      return addNoIndexHeaderIfNeeded(request, response);
    }

    const url = new URL(request.url);

    // RFC-0908: Trailing-slash normalization — enforce trailingSlash: "always" policy.
    // Redirect page routes without trailing slash to the same path with "/".
    // Done in the Worker (not _redirects) because run_worker_first: true causes
    // _redirects catch-all rules to loop infinitely.
    if (isPageRoute(url.pathname) && url.pathname !== "/" && !url.pathname.endsWith("/")) {
      const normalizedUrl = new URL(request.url);
      normalizedUrl.pathname = url.pathname + "/";
      return Response.redirect(normalizedUrl.toString(), 308);
    }

    if (!isPageRoute(url.pathname)) {
      const response = await astroHandler.fetch(request, env, ctx);
      return addNoIndexHeaderIfNeeded(request, response);
    }

    const accept = request.headers.get("Accept") ?? "";
    if (!accept.includes("text/markdown")) {
      const response = await astroHandler.fetch(request, env, ctx);
      return addNoIndexHeaderIfNeeded(request, addVaryAccept(response));
    }

    const twinPath = markdownTwinUrlPath(url.pathname, { supportedLangs: SUPPORTED_LANGS });
    const twinUrl = new URL(twinPath, url.origin);
    const twinResponse = await (env.ASSETS as Fetcher).fetch(new Request(twinUrl.toString()));
    if (!twinResponse.ok) {
      const response = await astroHandler.fetch(request, env, ctx);
      return addNoIndexHeaderIfNeeded(request, addVaryAccept(response));
    }

    const body = await twinResponse.text();
    const response = new Response(body, {
      status: 200,
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Vary": "Accept",
        "Cache-Control": "public, max-age=300",
      },
    });
    return addNoIndexHeaderIfNeeded(request, response);
  },
};
